INSERT INTO `district` (`dist_name`) VALUES
('Bagerhat'),
('Bandarban'),
('Barguna'),
('Barisal'),
('Bhola'),
('Bogura'),
('Brahmanbaria'),
('Chandpur'),
('Chapainawabganj'),
('Chattogram'),
('Chuadanga'),
('Cumilla'),
('Cox''s Bazar'),
('Dhaka'),
('Dinajpur'),
('Faridpur'),
('Feni'),
('Gaibandha'),
('Gazipur'),
('Gopalganj'),
('Habiganj'),
('Jamalpur'),
('Jashore'),
('Jhalokathi'),
('Jhenaidah'),
('Joypurhat'),
('Khagrachari'),
('Khulna'),
('Kishoreganj'),
('Kushtia'),
('Lakshmipur'),
('Lalmonirhat'),
('Madaripur'),
('Magura'),
('Manikganj'),
('Meherpur'),
('Moulvibazar'),
('Munshiganj'),
('Mymensingh'),
('Naogaon'),
('Narail'),
('Narayanganj'),
('Narsingdi'),
('Natore'),
('Netrokona'),
('Nilphamari'),
('Noakhali'),
('Pabna'),
('Panchagarh'),
('Patuakhali'),
('Pirojpur'),
('Rajbari'),
('Rajshahi'),
('Rangamati'),
('Rangpur'),
('Satkhira'),
('Shariatpur'),
('Sherpur'),
('Sirajganj'),
('Sunamganj'),
('Sylhet'),
('Tangail'),
('Thakurgaon'),
('Narayanganj');

-- Insert 10 sample data into user table
INSERT INTO `user` (`email`, `password`, `address`) VALUES
('a@e.c', 'qwe123', 'Address 1'),
('g@e.c', 'qwe123', 'Address 2'),
('b@e.c', 'qwe123', 'Address 3'),
('user4@example.com', 'password4', 'Address 4'),
('user5@example.com', 'password5', 'Address 5'),
('user6@example.com', 'password6', 'Address 6'),
('user7@example.com', 'password7', 'Address 7'),
('user8@example.com', 'password8', 'Address 8'),
('user9@example.com', 'password9', 'Address 9'),
('user10@example.com', 'password10', 'Address 10');

-- Insert 10 sample data into name table
INSERT INTO `name` (`first_name`, `last_name`, `user_id`) VALUES
('John', 'Doe', 1),
('Jane', 'Doe', 2),
('Alice', 'Johnson', 3),
('Bob', 'Smith', 4),
('Eva', 'Brown', 5),
('Charlie', 'Miller', 6),
('Olivia', 'Davis', 7),
('Daniel', 'Wilson', 8),
('Sophia', 'Moore', 9),
('Jackson', 'Taylor', 10);

-- Insert 10 sample data into phone table
INSERT INTO `phone` (`phone_number`, `user_id`) VALUES
('123-456-7890', 1),
('987-654-3210', 2),
('555-123-4567', 3),
('555-987-6543', 4),
('555-111-2222', 5),
('555-333-4444', 6),
('555-555-5555', 7),
('555-777-8888', 8),
('555-999-0000', 9),
('555-123-7890', 10);

-- Insert 10 sample data into auth table
INSERT INTO `auth` (`user_id`, `type`) VALUES
(1, 'admin'),
(2, 'general'),
(3, 'busDriver'),
(4, 'admin'),
(5, 'general'),
(6, 'busDriver'),
(7, 'admin'),
(8, 'general'),
(9, 'busDriver'),
(10, 'admin');

INSERT INTO `driver` (`driver_license_no`, `driver_license_exp`, `user_id`) VALUES
('DL123456', '2023-12-31', 3),
('DL555555', '2023-10-20', 6),
('DL999000', '2023-09-15', 9);